on:
  workflow_dispatch:
  schedule:
    - cron: '53 * * * *'

name: Timed GA

jobs:
  timed_action:
    name: Timed action
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "Hello world!"
