on:
  workflow_dispatch:
  schedule:
    - cron: '30,40,50 * * * *'
      timezone: "America/New_York"

name: Timed GA

jobs:
  timed_action:
    name: Timed action
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "Hello world!"
