on:
  workflow_dispatch:
  schedule:
    - cron: '43 * * * *'

name: Timed GitHub Action

jobs:
  timed_action:
    name: Job for timed action
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello world!"
